exports.user = require('./user')
exports.auth = require('./auth')
exports.tag = require('./tag')
exports.article = require('./article')
exports.term = require('./term')
exports.lesson = require('./lesson')
exports.exam = require('./exam')
